services:
  pokedex:
    build:
      context: ./pokedex-app
    ports:
      - "2222:2222"
    volumes:
      - ./pokedex-app/src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - pokedex-net

networks:
  pokedex-net:
    name: pokedex-net
